name: SonarCloud
on:
  push:
    branches:
      - main

jobs:
  slack_notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/

      - name: Build Maven project
        run: |
          mvn clean install
          # $env:MAVEN_EXIT_CODE=$LASTEXITCODE

      - name: Generate code coverage report
        run: |
          mvn jacoco:report

      - name: Publish code coverage result
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: target/site/jacoco/index.html

      - name: Convert to non-shallow clone
        run: git fetch --unshallow

      - name: Set JFrog CLI Path
        run: export PATH=$PATH:/usr/local/bin

      - name: Push Artifacts to JFrog
        run: |
          jfrog rt u target/*.jar artifacts_pocs-libs-snapshot-local/ --url=https://aritfacts.jfrog.io/artifactory/artifacts_pocs-libs-snapshot-local/ --access-token=YOUR_JFROG_ACCESS_TOKEN

      # Uncomment the following block if you want to include SonarQube scan
      # - name: SonarQube Scan
      #   run: mvn sonar:sonar -Dsonar.organization=YOUR_SONAR_ORG_KEY -Dsonar.projectKey=YOUR_PROJECT_KEY -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=YOUR_SONAR_TOKEN

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven project built successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Maven build failed. Please check the build logs for details."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
